var crash = new Audio()
crash.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/crash.mp3"
var kickbass = new Audio()
kickbass.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/kickbass.mp3"
var snare = new Audio()
snare.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/snare.mp3"
var tom1 = new Audio()
tom1.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/tom1.mp3"
var tom2 = new Audio()
tom2.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/tom2.mp3"
var tom3 = new Audio()
tom3.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/tom3.mp3"
var tom4 = new Audio()
tom4.src = "/home/shivam/Desktop/Amfoss-tasks/task-08/sounds/tom4.mp3"
